WIP: First stab at implementation

diff --git a/bin/addOrUpdateBlock b/bin/addOrUpdateBlock
--- a/bin/addOrUpdateBlock
+++ b/bin/addOrUpdateBlock
@@ -1,10 +1,15 @@
 #!/bin/bash
 
+literalPattern()
+{
+    sed -e 's/[][\$*.^]/\\&/g'
+}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-i[SUFFIX]|--in-place[=SUFFIX]|-t|--test-only] [--ignore-nonexisting|--create-nonexisting] [--add-after ADDRESS] -m|-marker WHAT|(--begin-marker BEGIN-LINE --end-marker END-LINE) -b|--block-text BLOCK-TEXT|-B|--block-file BLOCK-FILE [-a|--accept-match ACCEPT-PATTERN] [--pre-line PRETEXT [--pre-line ...]|--post-line POSTTEXT [--post-line ...]]] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-i[SUFFIX]|--in-place[=SUFFIX]|-t|--test-only] [--ignore-nonexisting|--create-nonexisting] [--add-after ADDRESS] -m|-marker WHAT|(--begin-marker BEGIN-LINE --end-marker END-LINE) -b|--block-text BLOCK-TEXT|-B|--block-file BLOCK-FILE [...] [-a|--accept-match ACCEPT-PATTERN] [--pre-line PRETEXT [--pre-line ...]|--post-line POSTTEXT [--post-line ...]]] [FILE ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -61,6 +66,7 @@ HELPDESCRIPTION
 			    (This is assumed to be for comments or headers that
 			    would already be there.)
     --post-line POSTTEXT    When a fresh BLOCK is added, put POSTTEXT after it.
+
 EXIT STATUS:
     0	An update has happened.
     1	The BLOCK already existed, no modifications were made.
@@ -68,12 +74,14 @@ EXIT STATUS:
     3	Internal error or failed assertion.
     4	None of the passed FILE(s) exist; no modifications could be made.
     5	A FILE could not be created / modified (due to problems with sed).
+    6	The BLOCK-FILE cannot be read.
 
 Example:
 HELPTEXT
     printf '%q %s\n' "$(basename "$1")" '-i.bak --marker "home network" --block path/to/myhosts.txt /etc/hosts'
 }
 
+readonly NL=$'\n'
 isTestOnly=
 isAll=
 isIgnoreNonexisting=
@@ -81,11 +89,11 @@ isCreateNonexisting=
 typeset -a sedInplaceArgs=()
 beginMarker=
 endMarker=
-blockText=
-blockFilespec=
+unset insertableBlockText
+literalBlockTextPattern=
 acceptMatch=
-unset preLines
-unset postLines
+unset insertablePreLines
+unset insertablePostLines
 addAfterAddress='$'
 while [ $# -ne 0 ]
 do
@@ -99,21 +107,30 @@ do
 			    shift; isIgnoreNonexisting=t;;
 	--create-nonexisting)
 			    shift; isCreateNonexisting=t;;
-	--marker|-m)	    shift; beginMarker="# BEGIN${1:+ }$1"; endMarker="# END${1:+ }$1"; shift;;
-	--begin-marker)	    shift; beginMarker="$1"; shift;;
-	--end-marker)	    shift; endMarker="$1"; shift;;
-	--block-text|-b)    shift; blockText="$1"; shift;;
-	--block-file|-B)    shift; blockFilespec="$1"; shift;;
+	--marker|-m)	    shift; beginMarker="# BEGIN${1:+ }${1//$'\n'/ }"; endMarker="# END${1:+ }${1//$'\n'/ }"; shift;;
+	--begin-marker)	    shift; beginMarker="${1//$'\n'/ }"; shift;;
+	--end-marker)	    shift; endMarker="${1//$'\n'/ }"; shift;;
+	--block-file|-B)    shift
+			    text="$(<"$1")" || exit 6
+			    shift
+			    escapedText="${text//\\/\\\\}"; insertableBlockText="${insertableBlockText}${insertableBlockText:+\\$NL}${escapedText//${NL}/\\$NL}"
+			    literalBlockTextPattern="${literalBlockTextPattern}${literalBlockTextPattern:+\\n}$(printf %s "${text//${NL}/\\n}" | literalPattern)"
+			    ;;
+	--block-text|-b)    shift
+			    escapedText="${1//\\/\\\\}"; insertableBlockText="${insertableBlockText}${insertableBlockText:+\\$NL}${escapedText//${NL}/\\$NL}"
+			    literalBlockTextPattern="${literalBlockTextPattern}${literalBlockTextPattern:+\\n}$(printf %s "${1//${NL}/\\n}" | literalPattern)"
+			    shift
+			    ;;
 	--accept-match|-a)  shift; acceptMatch="$1"; shift;;
-	--pre-line)	    shift; escapedLine="${1//\//\\/}"; preLines="${preLines}${preLines:+\\$NL}${escapedLine//${NL}/\\$NL}"; shift;;
-	--post-line)	    shift; escapedLine="${1//\//\\/}"; postLines="${postLines}${postLines:+\\$NL}${escapedLine//${NL}/\\$NL}"; shift;;
+	--pre-line)	    shift; escapedLine="${1//\\/\\\\}"; insertablePreLines="${insertablePreLines}${insertablePreLines:+\\$NL}${escapedLine//${NL}/\\$NL}"; shift;;
+	--post-line)	    shift; escapedLine="${1//\\/\\\\}"; insertablePostLines="${insertablePostLines}${insertablePostLines:+\\$NL}${escapedLine//${NL}/\\$NL}"; shift;;
 	--add-after)	    shift; addAfterAddress="$1"; shift;;
 	--)		    shift; break;;
 	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		    break;;
     esac
 done
-if [ -z "$blockText" -a -z "$blockFilespec" ]; then
+if [ -z "${insertableBlockText+t}" ]; then
     echo 'ERROR: No BLOCK passed; use either -b|--block-text BLOCK-TEXT or -B|--block-file BLOCK-FILE.'
     echo
     printUsage "$0"
@@ -144,3 +161,136 @@ elif [ -n "$isIgnoreNonexisting" -a -n "$isCreateNonexisting" ]; then
     printUsage "\$1"
     exit 2
 fi >&2
+
+literalBeginMarkerPattern="$(printf %s "$beginMarker" | literalPattern)"
+literalEndMarkerPattern="$(printf %s "$endMarker" | literalPattern)"
+insertableBeginMarker="${beginMarker//\\/\\\\}"
+insertableEndMarker="${endMarker//\\/\\\\}"
+[ $# -eq 0 ] && set -- -    # Read from stdin if no FILE is passed.
+
+create()
+{
+    local filespec="$1"; shift
+    # If the file is completely empty, sed treats this as zero lines, and no
+    # address (not 1, not $) will match; the whole invocation would be a no-op.
+    # Therefore, start with a single empty line, and change that one instead.
+    echo > "$filespec" || return 1
+
+    local insertableContent=
+    [ -n "${insertablePreLines+t}" ] && insertableContent="${insertableContent}${insertablePreLines}\\${NL}"
+    insertableContent="${insertableContent}${insertableBlockText}"
+    [ -n "${insertablePostLines+t}" ] && insertableContent="${insertableContent}\\${NL}${insertablePostLines}"
+    typeset -a sedProgram=(
+	-e "\$c\\${NL}${insertableContent}"
+    )
+
+    sed "${sedInplaceArgs[@]}" \
+	"${sedProgram[@]}" \
+	-- "$filespec"
+}
+process()
+{
+    local isAppend="$1"; shift
+    local filespec="$1"; shift
+
+    typeset -a sedProgram=()
+    if [ "$acceptMatch" ]; then
+	sedProgram+=(
+	    # If ACCEPT-PATTERN matches, put a newline (as that can never be
+	    # matched as a previous block) into the hold space to signal that
+	    # there's already a match.
+	    -e "/${acceptMatch//\//\\/}/{ x; s/.*/\\n/; x; b last; }"
+	)
+    fi
+
+    sedProgram+=(
+	# If there already has been a match (determined via the hold space, see
+	# next), don't update following lines. Else, search for the end marker.
+	-e "/^${literalBeginMarkerPattern//\//\\/}\$/{ x; /./{ x; b last; }; x; p; s/.*//; \$b; N; s/^\\n//; b searchForEnd }"
+	-e 'b'
+	-e ':searchForEnd'
+	# Another begin marker resets the search.
+	-e "/\\(^\\|\\n\\)${literalBeginMarkerPattern//\//\\/}\$/{ p; s/.*//; \$b; N; s/^\\n//; b searchForEnd }"
+	# Keep reading until we find the end marker.
+	-e "/\\(^\\|\\n\\)${literalEndMarkerPattern//\//\\/}\$/!{ \$b; N; b searchForEnd }"
+	# If we find the end marker, duplicate the previous block into the hold
+	# space; this serves as a marker that we have done an update and also
+	# that we don't need to append the line at the end.
+	# Then exchange the previous block with the new block and the end marker.
+	-e "h; s/.*//; c\\${NL}${insertableBlockText}\\${NL}${endMarker//\\/\\\\}"
+    )
+
+    sedProgram+=(
+	-e ':last'
+	# On the last line, we check the hold space. If it's identical to the
+	# new block, no processing actually has happened, and we indicate an
+	# error. If the hold space isn't empty, skip further processing (i.e.
+	# appending), as we've already done the update.
+	-e "${addAfterAddress}{ x; /^\\n\$\\|^${literalBlockTextPattern//\//\\/}\\n${literalEndMarkerPattern//\//\\/}\$/{ x; q 98 }; /./{ x; b; }; x; }"
+    )
+
+    if [ "$isAppend" ]; then
+	# Else append LINE.
+	if [ -n "${insertablePreLines+t}" ]; then
+	    sedProgram+=(
+		-e "${addAfterAddress}a\\${NL}${insertablePreLines}"
+	    )
+	fi
+	sedProgram+=(
+	    -e "${addAfterAddress}a\\${NL}${insertableBeginMarker}\\${NL}${insertableBlockText}\\${NL}${insertableEndMarker}"
+	)
+	if [ -n "${insertablePostLines+t}" ]; then
+	    sedProgram+=(
+		-e "${addAfterAddress}a\\${NL}${insertablePostLines}"
+	    )
+	fi
+    else
+	sedProgram+=(
+	    # Indicate no update via special exit status.
+	    -e '$q 99'
+	)
+    fi
+#echo >&3 "****"  "${sedProgram[@]}"
+    sed "${sedInplaceArgs[@]}" \
+	"${sedProgram[@]}" \
+	-- "$filespec"
+}
+
+let existingCount=0
+for ((i = 1; i <= $#; i++))
+do
+    filespec="${@:$i:1}"
+    if [ "$filespec" = '-' -o -e "$filespec" ]; then
+	let existingCount+=1
+    elif [ "$isCreateNonexisting" ]; then
+	create "$filespec"
+	status=$?
+	case $status in
+	    0)	[ "$isAll" ] || exit $status;;
+	    *)	status=5;;
+	esac
+	let existingCount+=1
+	continue
+    else
+	continue
+    fi
+
+    isAppend=; [ -n "$isAll" -o $i -eq $# ] && isAppend=t
+
+    eval 'process "$isAppend" "$filespec"' "${isTestOnly:+>/dev/null}"
+    status=$?
+    case $status in
+	0)	[ "$isAll" ] || exit $status;;
+	98|99)	status=1;;
+	*)	status=5;;
+    esac
+done
+
+if [ $existingCount -eq 0 ]; then
+    if [ -n "$isIgnoreNonexisting" ]; then
+	status=0
+    else
+	status=4
+    fi
+fi
+exit $status
