Minor: Consistently use printUsage(), add newline before bottom hint

diff --git a/bin/addOrUpdate b/bin/addOrUpdate
--- a/bin/addOrUpdate
+++ b/bin/addOrUpdate
@@ -16,7 +16,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -109,24 +109,24 @@ do
 	--post-line)	    shift; escapedLine="${1//\//\\/}"; postLines="${postLines}${postLines:+\\$NL}${escapedLine//${NL}/\\$NL}"; shift;;
 	--add-after)	    shift; addAfterAddress="$1"; shift;;
 	--)		    shift; break;;
-	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		    break;;
     esac
 done
 if [ -z "$line" ]; then
     echo >&2 'ERROR: No LINE passed.'
     echo >&2
-    printShortUsage "$0" >&2
+    printUsage "$0" >&2
     exit 2
 elif [ ${#sedInplaceArgs[@]} -gt 0 -a -n "$isTestOnly" ]; then
     echo >&2 'ERROR: Cannot combine --in-place and --test-only.'
     echo >&2
-    printShortUsage "\$1" >&2
+    printUsage "\$1" >&2
     exit 2
 elif [ -n "$isIgnoreNonexisting" -a -n "$isCreateNonexisting" ]; then
     echo >&2 'ERROR: Cannot combine --ignore-nonexisting and --create-nonexisting.'
     echo >&2
-    printShortUsage "\$1" >&2
+    printUsage "\$1" >&2
     exit 2
 fi
 
diff --git a/bin/containedOrAddOrUpdate b/bin/containedOrAddOrUpdate
--- a/bin/containedOrAddOrUpdate
+++ b/bin/containedOrAddOrUpdate
@@ -11,7 +11,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -67,6 +67,7 @@ do
 	--accept-match|-a|--update-match|-u|--replacement|-r|--pre-line|--post-line|--add-after)
 				    addOrUpdateArgs+=("$1" "$2"); shift; shift;;
 	--)			    addOrUpdateArgs+=("$1"); shift; break;;
+	-*)			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)			    break;;
     esac
 done
diff --git a/bin/onbag b/bin/onbag
--- a/bin/onbag
+++ b/bin/onbag
@@ -33,7 +33,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -181,7 +181,7 @@ do
 	--stop-on|-s)	shift; stopPattern="$1"; shift; onchangeArgs=(--exit-on $EXIT_SIGNAL);;
 	--rate-limit)	shift; rateLimit="$1"; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
@@ -195,7 +195,7 @@ fi
 if [ ! "$isPrint" ] && [ ! "$count" ] && [ ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: Need to pass either -1|-c|--count to count changes, --print to show updated files, or -c|--command to execute a command.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ -n "$exitOn" -a -n "$retryOn" -a "$exitOn" = "$retryOn" -a "$exitComparison" = "$retryComparison" ]; then
     printf 'ERROR: Cannot exit and retry on the same exit status (%d).\n' "$exitOn"
diff --git a/bin/onfile b/bin/onfile
--- a/bin/onfile
+++ b/bin/onfile
@@ -27,7 +27,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -206,7 +206,7 @@ do
 	--stop-on-filename|-s)	shift; stopFilenamePattern="$1"; shift;;
 	--rate-limit)		shift; rateLimit="$1"; shift;;
 	--)			shift; break;;
-	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)			break;;
     esac
 done
@@ -220,12 +220,12 @@ fi
 if [ -z "${dir}${glob}${sourceCommand}" ]; then
     echo 'ERROR: No -d|--dir DIR|-g|--glob 'GLOB'|--source-command SOURCE-COMMAND passed.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ -n "$glob" -a -n "$sourceCommand" ]; then
     echo "ERROR: Can only pass either -g|--glob 'GLOB' or --source-command SOURCE-COMMAND."
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ -n "$dir" -a ! -d "$dir" ]; then
     printf 'ERROR: The directory %s does not exist.\n' "$dir"
@@ -233,12 +233,12 @@ elif [ -n "$dir" -a ! -d "$dir" ]; then
 elif [ -n "$dir" ] && ! cd "$dir"; then
     exit $?
 elif [ "$isDeleteEmptyFile" ] && [ ! "$isStopOnEmptyFile" ]; then
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 elif [ ! "$isPrint" ] && [ ! "$count" ] && [ ${#commands[@]} -eq 0 ]; then
     echo 'ERROR: Need to pass either -1|-c|--count to count changes, --print to show updated files, or -c|--command to execute a command.'
     echo
-    printShortUsage "$0"
+    printUsage "$0"
     exit 2
 fi >&2
 if [ -n "$exitOn" -a -n "$isParallel" ]; then
diff --git a/bin/succeedsOr b/bin/succeedsOr
--- a/bin/succeedsOr
+++ b/bin/succeedsOr
@@ -10,7 +10,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -59,11 +59,11 @@ if [ $# -ne 0 ]; then
     fi
 fi
 if [ ${#commands[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
-    echo >&2
-    printUsage "$0" >&2
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 if [ "$isRecheckAtCheckpoints" ]; then
     printf -v quotedTestCommandLine '%q ' "${commands[@]}"
     checkpointPrePipeline=(sed -e "1i\\checkpoint() { ${isNeedEval:+eval }${quotedTestCommandLine//\\/\\\\}>/dev/null 2>&1 && exit 0; }")
diff --git a/bin/tempdir b/bin/tempdir
--- a/bin/tempdir
+++ b/bin/tempdir
@@ -5,7 +5,9 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-d|--or-existing DIRSPEC] [-n|--name NAME] [-c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...]] [-?|-h|--help]'
+    echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[-d|--or-existing DIRSPEC] [-n|--name NAME] -|--stdin'
+    echo
     printf 'Usage: %q %s <<EOF\n  COMMANDLINE\n...\nEOF\n' "$(basename "$1")" '[...] -|--stdin'
 }
 printUsage()
@@ -13,7 +15,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -47,7 +49,7 @@ do
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--stdin|-)	shift; isStdin=t;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/withPath b/bin/withPath
--- a/bin/withPath
+++ b/bin/withPath
@@ -5,7 +5,9 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" 'ADD-PATH [-C|--clean] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    echo
     printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" 'ADD-PATH [-C|--clean] [--bare|[--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--emulate-prompt] [--worst-status]]'
+    echo
     printf 'Usage: %q %s <<EOF\n  COMMANDLINE\n...\nEOF\n' "$(basename "$1")" 'ADD-PATH [...]'
 }
 printUsage()
@@ -13,7 +15,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -38,10 +40,11 @@ case "$1" in
 esac
 
 if [ $# -eq 0 ]; then
-    echo >&2 'ERROR: No ADD-PATH passed.'
-    printShortUsage "$0" >&2
+    echo 'ERROR: No ADD-PATH passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 pathAdd="${1?}"
 export PATH_OVERRIDE=true
 export PATH="${pathAdd}:$PATH"; shift
@@ -60,7 +63,7 @@ do
 	--no-trailing-prompt|--trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--emulate-prompt|--worst-status)  runWithPromptArgs+=("$1"); shift;;
 	--no-count-on)	runWithPromptArgs+=("$1" "$2"); shift; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
