WIP: Ensure that begin and end markers are not identical

diff --git a/bin/addOrUpdateBlock b/bin/addOrUpdateBlock
--- a/bin/addOrUpdateBlock
+++ b/bin/addOrUpdateBlock
@@ -128,6 +128,11 @@ elif [ -z "$endMarker" ]; then
     echo
     printUsage "$0"
     exit 2
+elif [ "$beginMarker" = "$endMarker" ]; then
+    echo 'ERROR: BEGIN-LINE and END-LINE must be different.'
+    echo
+    printUsage "$0"
+    exit 2
 elif [ ${#sedInplaceArgs[@]} -gt 0 -a -n "$isTestOnly" ]; then
     echo 'ERROR: Cannot combine --in-place and --test-only.'
     echo
