bag-consume: We need the marker file to react on a parallel COMMAND's exit status here as well

diff --git a/bin/bag-consume b/bin/bag-consume
--- a/bin/bag-consume
+++ b/bin/bag-consume
@@ -225,6 +225,12 @@ if [ ! "$isPrint" ] && [ ${#commands[@]} -eq 0 ]; then
     printUsage "$0"
     exit 2
 fi >&2
+if [ -n "$exitOn" -a -n "$isParallel" ]; then
+    # Need a marker file to signal stopping; a variable won't do.
+    keepRunningMarkerFile=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$$RANDOM")
+    touch "$keepRunningMarkerFile"
+fi
+
 # Don't show a prompt if nothing was printed; this would just waste screen
 # space. Parallel execution is supposedly mostly used to control resource usage
 # (e.g. just one instance via singleton or not too frequent actions via
@@ -297,11 +303,21 @@ triggerCommand()
 	[ -n "$appendAfterText" ] && bag "${bagArgs[@]}" --append -- "$appendAfterText"
     fi
     if [ "$exitOn" ] && [ $exitStatus $exitComparison $exitOn ]; then
+	[ "$isParallel" ] && kill -SIGUSR1 $$
 	exit $exitStatus
     fi
 }
 
 
+shutdown()
+{
+    if [ -e "$keepRunningMarkerFile" ]; then
+	rm -f "$keepRunningMarkerFile"
+	wait    # Wait for running jobs to finish; this avoids the "Terminated" message and exit status 143.
+    fi
+    exit 0
+}
+trap "shutdown" SIGUSR1
 if [ -n "$pgid" ]; then
     trap "kill -- -$pgid" EXIT  # If we're the leader, kill subshell processes when the script exits.
 else
