[on]bag[-consume]: BUG: Interactive use prints "Terminated" and exits with 143
New on Ubuntu 24.04 with Bash 5.2.21(1)-release, but I could also reproduce with my singleton script on Ubuntu 20.04 / Bash 5.0.17(1)-release.
Prevent the current script from terminating by clearing the signal handler.

diff --git a/bin/bag-consume b/bin/bag-consume
--- a/bin/bag-consume
+++ b/bin/bag-consume
@@ -628,7 +628,7 @@ shutdown()
 trap "shutdown" SIGUSR1
 
 if [ -n "$pgid" ]; then
-    trap "markerDrop; kill -- -$pgid" EXIT  # If we're the leader, kill subshell processes when the script exits.
+    trap "markerDrop; trap '' SIGTERM; kill -- -$pgid" EXIT  # If we're the leader, kill subshell processes when the script exits. Don't kill ourselves when we kill the process group; this would print "Terminated" and change the exit status to 143. We're about to exit, anyway.
 else
     trap "markerDrop; jobs -p | xargs --no-run-if-empty kill --" EXIT  # Someone else is the leader; killing remaining jobs is all we can do here.
 fi
