containedOrAddOrUpdateLine: CHG: Do not forward --test-only but return early and also offer a custom message via --needs-update-message

diff --git a/bin/containedOrAddOrUpdateLine b/bin/containedOrAddOrUpdateLine
--- a/bin/containedOrAddOrUpdateLine
+++ b/bin/containedOrAddOrUpdateLine
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-g|--memoize-group GROUP] [--name NAME] [-M|--up-to-date-message MSG] [-i[SUFFIX]|--in-place[=SUFFIX]] [--ignore-nonexisting|--create-nonexisting] [--add-after ADDRESS] -l|--line LINE [-a|--accept-match ACCEPT-PATTERN -u|--update-match PATTERN [-r|--replacement REPLACEMENT] [--pre-line PRETEXT [--pre-line ...]|--post-line POSTTEXT [--post-line ...]]] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-g|--memoize-group GROUP] [--name NAME] [-m|--needs-update-message MSG] [-M|--up-to-date-message MSG] [-i[SUFFIX]|--in-place[=SUFFIX]] [--ignore-nonexisting|--create-nonexisting] [--add-after ADDRESS] -l|--line LINE [-a|--accept-match ACCEPT-PATTERN -u|--update-match PATTERN [-r|--replacement REPLACEMENT] [--pre-line PRETEXT [--pre-line ...]|--post-line POSTTEXT [--post-line ...]]] [FILE ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -32,6 +32,10 @@ HELPDESCRIPTION
 			    FILE(s) (will be used for querying and memoizing the
 			    decision). Defaults to the passed FILE(s)
 			    themselves.
+    --needs-update-message|-m MSG
+			    Print MSG (instead of a message synthesized from
+			    FILE and NAME) to standard error if --test-only and
+			    the FILE requires an update.
     --up-to-date-message|-M MSG
 			    Print MSG (instead of a message synthesized from
 			    FILE and NAME) to standard error if the LINE already
@@ -52,9 +56,10 @@ HELPTEXT
 
 typeset -a addOrUpdateLineArgs=()
 typeset -a addOrUpdateLineInplaceArg=()
-typeset -a addOrUpdateLineTestOnlyArg=()
 typeset -a memoizeDecisionArgs=()
+isTestOnly=
 name=
+unset needsUpdateMessage
 unset upToDateMessage
 isAll=
 line=
@@ -64,9 +69,10 @@ do
 	--help|-h|-\?)		    shift; printLongUsage "$0"; exit 0;;
 	--memoize-group|-g)	    memoizeDecisionArgs+=("$1" "$2"); shift; shift;;
 	--name|-n)		    shift; name="$1"; shift;;
+	--needs-update-message|-m)  shift; needsUpdateMessage="$1"; shift;;
 	--up-to-date-message|-M)    shift; upToDateMessage="$1"; shift;;
 	--in-place|--inplace=*|-i*) addOrUpdateLineInplaceArg+=("$1"); shift;;
-	--test-only|-t)		    addOrUpdateLineTestOnlyArg+=("$1"); shift;;
+	--test-only|-t)		    shift; isTestOnly=t;;
 	--all|-a)		    addOrUpdateLineArgs+=("$1"); shift; isAll=t;;
 	--line|-l)		    addOrUpdateLineArgs+=("$1" "$2"); line="$2"; shift; shift;;
 	--ignore-nonexisting|--create-nonexisting)
@@ -112,7 +118,15 @@ fi
 # --test-only.
 addOrUpdateLine --test-only "${addOrUpdateLineArgs[@]}" "$@"
 case $? in
-    0)	;;
+    0)	if [ "$isTestOnly" ]; then
+	    if [ -z "${needsUpdateMessage+t}" ]; then
+		printf >&2 "%s %s contain '%s'; update required.\\n" "${name:-$subject}" "$verb" "$line"
+	    elif [ -n "$needsUpdateMessage" ]; then
+		printf >&2 "%s\n" "$needsUpdateMessage"
+	    fi
+	    exit 0
+	fi
+	;;
     1)	if [ -z "${upToDateMessage+t}" ]; then
 	    printf >&2 "%s already %s '%s'; no update necessary.\\n" "${name:-$subject}" "$negativeVerb" "$line"
 	elif [ -n "$upToDateMessage" ]; then
@@ -128,7 +142,7 @@ esac
 memoizeDecision "${memoizeDecisionArgs[@]}" --subject "${name:-$subject}" --verb "$verb" --state "yet contain '$line'" --action "$action"
 status=$?
 case $status in
-    0)	exec addOrUpdateLine "${addOrUpdateLineInplaceArg[@]}" "${addOrUpdateLineTestOnlyArg[@]}" "${addOrUpdateLineArgs[@]}" "$@";;
+    0)	exec addOrUpdateLine "${addOrUpdateLineInplaceArg[@]}" "${addOrUpdateLineArgs[@]}" "$@";;
     1)	exit 99;;
     *)	exit $status;;
 esac
