containedOrAddOrUpdateBlock: CHG: Do not forward --test-only but return early and also offer a custom message via --needs-update-message

diff --git a/bin/containedOrAddOrUpdateBlock b/bin/containedOrAddOrUpdateBlock
--- a/bin/containedOrAddOrUpdateBlock
+++ b/bin/containedOrAddOrUpdateBlock
@@ -4,7 +4,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-g|--memoize-group GROUP] [--name NAME] [-M|--up-to-date-message] [--what WHAT] [-i[SUFFIX]|--in-place[=SUFFIX]] [--ignore-nonexisting|--create-nonexisting] [--add-after ADDRESS] -m|-marker WHAT|(--begin-marker BEGIN-LINE --end-marker END-LINE) -b|--block-text BLOCK-TEXT|-B|--block-file BLOCK-FILE [...] [-a|--accept-match ACCEPT-PATTERN] [--pre-line PRETEXT [--pre-line ...]|--post-line POSTTEXT [--post-line ...]]] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-g|--memoize-group GROUP] [--name NAME] [-m|--needs-update-message MSG] [-M|--up-to-date-message] [--what WHAT] [-i[SUFFIX]|--in-place[=SUFFIX]] [--ignore-nonexisting|--create-nonexisting] [--add-after ADDRESS] -m|-marker WHAT|(--begin-marker BEGIN-LINE --end-marker END-LINE) -b|--block-text BLOCK-TEXT|-B|--block-file BLOCK-FILE [...] [-a|--accept-match ACCEPT-PATTERN] [--pre-line PRETEXT [--pre-line ...]|--post-line POSTTEXT [--post-line ...]]] [FILE ...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -38,6 +38,10 @@ HELPDESCRIPTION
 			    BLOCK (will be used for querying and memoizing the
 			    decision). Defaults to the --marker|-m WHAT
 			    argument, if given, or "the block".
+    --needs-update-message|-m MSG
+			    Print MSG (instead of a message synthesized from
+			    FILE and NAME) to standard error if --test-only and
+			    the FILE requires an update.
     --up-to-date-message|-M MSG
 			    Print MSG (instead of a message synthesized from
 			    FILE and WHAT / NAME) to standard error if the BLOCK
@@ -59,11 +63,12 @@ HELPTEXT
 
 typeset -a addOrUpdateBlockArgs=()
 typeset -a addOrUpdateBlockInplaceArg=()
-typeset -a addOrUpdateBlockTestOnlyArg=()
 typeset -a memoizeDecisionArgs=()
+isTestOnly=
 name=
 isAll=
 what=
+unset needsUpdateMessage
 unset upToDateMessage
 markerName=
 while [ $# -ne 0 ]
@@ -73,9 +78,10 @@ do
 	--memoize-group|-g)	    memoizeDecisionArgs+=("$1" "$2"); shift; shift;;
 	--name|-n)		    shift; name="$1"; shift;;
 	--what)			    shift; what="$1"; shift;;
+	--needs-update-message|-m)  shift; needsUpdateMessage="$1"; shift;;
 	--up-to-date-message|-M)    shift; upToDateMessage="$1"; shift;;
 	--in-place|--inplace=*|-i*) addOrUpdateBlockInplaceArg+=("$1"); shift;;
-	--test-only|-t)		    addOrUpdateBlockTestOnlyArg+=("$1"); shift;;
+	--test-only|-t)		    shift; isTestOnly=t;;
 	--all|-a)		    addOrUpdateBlockArgs+=("$1"); shift; isAll=t;;
 	--marker|-m)		    addOrUpdateBlockArgs+=("$1" "$2"); markerName="$2"; shift; shift;;
 	--begin-marker|--end-marker|--block-text|-b|--block-file|-B|--accept-match|-a|--pre-line|--post-line|--add-after)
@@ -121,7 +127,15 @@ fi
 # --test-only.
 addOrUpdateBlock --test-only "${addOrUpdateBlockArgs[@]}" "$@"
 case $? in
-    0)	;;
+    0)	if [ "$isTestOnly" ]; then
+	    if [ -z "${needsUpdateMessage+t}" ]; then
+		printf >&2 "%s %s contain %s; update required.\\n" "${name:-$subject}" "$verb" "${what:-${markerName:-the block}}"
+	    elif [ -n "$needsUpdateMessage" ]; then
+		printf >&2 "%s\n" "$needsUpdateMessage"
+	    fi
+	    exit 0
+	fi
+	;;
     1)	if [ -z "${upToDateMessage+t}" ]; then
 	    printf >&2 "%s already %s %s; no update necessary.\\n" "${name:-$subject}" "$negativeVerb" "${what:-${markerName:-the block}}"
 	elif [ -n "$upToDateMessage" ]; then
@@ -137,7 +151,7 @@ esac
 memoizeDecision "${memoizeDecisionArgs[@]}" --subject "${name:-$subject}" --verb "$verb" --state "yet contain ${what:-${markerName:-the block}}" --action "$action"
 status=$?
 case $status in
-    0)	exec addOrUpdateBlock "${addOrUpdateBlockInplaceArg[@]}" "${addOrUpdateBlockTestOnlyArg[@]}" "${addOrUpdateBlockArgs[@]}" "$@";;
+    0)	exec addOrUpdateBlock "${addOrUpdateBlockInplaceArg[@]}" "${addOrUpdateBlockArgs[@]}" "$@";;
     1)	exit 99;;
     *)	exit $status;;
 esac
