eachArg: ENH: Add --between-command

diff --git a/bin/eachArg b/bin/eachArg
--- a/bin/eachArg
+++ b/bin/eachArg
@@ -7,7 +7,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--with-header|--with-prompt] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" | SIMPLECOMMAND [...] -- ARGUMENT [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--with-header|--with-prompt] [--between-command BETWEEN-COMMAND] [--usage-redirect COMMAND] -c|--command "COMMANDLINE" | SIMPLECOMMAND [...] -- ARGUMENT [...] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -32,6 +32,8 @@ HELPDESCRIPTION
 		    execution.
     --with-prompt   Emulate a full prompt (as if invoking COMMAND) before each
 		    execution.
+    --between-command BETWEEN-COMMAND
+		    Execute BETWEEN-COMMAND in between each COMMAND execution.
     --usage-redirect COMMAND
 		    When no ARGUMENT(s) are passed, redirect to COMMAND --help
 		    for usage instructions instead of printing this command's
@@ -59,6 +61,7 @@ done
 with=
 typeset -a commands=()
 typeset -a simpleCommands=()
+betweenCommand=
 usageRedirectCommand=
 while [ $# -ne 0 ]
 do
@@ -67,6 +70,8 @@ do
 	--command|-c)	shift; commands+=("$1"); isNeedEval=t; shift;;
 	--with-header)	shift; with=header;;
 	--with-prompt)	shift; with=prompt;;
+	--between-command)
+			shift; betweenCommand="$1"; shift;;
 	--usage-redirect)
 			shift; usageRedirectCommand="$1"; shift;;
 	--)		shift; break;;
@@ -111,6 +116,14 @@ case "$with" in
 	quoter='%q'; [ "$isNeedEval" ] && quoter='%s'
 	for arg
 	do
+	    if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
+		if [ "${betweenCommand:$((${#betweenCommand} - 1))}" = ';' ]; then
+		    printf '%s ' "$betweenCommand"  # Prepend the BETWEEN-COMMAND to the next ARGUMENT's execution (so there's no separate prompt) if it ends with a semicolon. Its exit status is then ignored.
+		else
+		    printf '%s\n' "$betweenCommand" # Use a separate prompt (and with it consider its exit status).
+		fi
+	    fi
+
 	    [ "$isNeedEval" ] && printf -v arg '%q' "$arg"
 	    typeset -a interpolatedCommands=("${commands[@]//"$argMarker"/$arg}")
 	    typeset -a a=("$arg")   # Quoter for isNeedEval=t is off, so need to use quoted arg here.
@@ -125,6 +138,10 @@ case "$with" in
 	status=0
 	for arg
 	do
+	    if [ ! "$isFirst" ] && [ -n "$betweenCommand" ]; then
+		eval "$betweenCommand" || { exitStatus=$?; if [ $exitStatus -gt $status ]; then status=$exitStatus; fi; }
+	    fi
+
 	    if [ "$with" = 'header' ]; then
 		header ${isFirst:+--first} "$arg"
 	    fi
