eachFile: Only chdir if --local-dir has been passed and the directory is not the current one

diff --git a/bin/eachFile b/bin/eachFile
--- a/bin/eachFile
+++ b/bin/eachFile
@@ -126,6 +126,7 @@ fi
 
 
 isFirst=t
+dirspec=.
 case "$with" in
     prompt)
 	quoter='%q'; [ "$isNeedEval" ] && quoter='%s'
@@ -149,7 +150,7 @@ case "$with" in
 	    typeset -a f=("$filespec")	# Quoter for isNeedEval=t is off, so need to use quoted arg here.
 	    [ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 
-	    printf 'cd %q && ' "$dirspec"
+	    printf 'cd %q && ' "$dirspec"   # Previous COMMANDS may have changed the directory, so unconditionally do the chdir.
 	    printf "$quoter " "${interpolatedCommands[@]}" "${f[@]}"
 	    printf '\n'
 	    isFirst=
@@ -169,9 +170,11 @@ case "$with" in
 
 	    if [ "$isLocalDir" ]; then
 		dirspec="$(dirname -- "$filespec")"
-		if ! cd "$dirspec" 2>/dev/null; then
-		    printf >&2 'ERROR: Cannot chdir to %s (for %s)!\n' "$dirspec" "$filespec"
-		    status=1; continue
+		if [ "$dirspec" != . -a "$dirspec" != "$PWD" ]; then
+		    if ! cd "$dirspec" 2>/dev/null; then
+			printf >&2 'ERROR: Cannot chdir to %s (for %s)!\n' "$dirspec" "$filespec"
+			status=1; continue
+		    fi
 		fi
 		filespec="$(basename -- "$filespec")"
 	    fi
