onbag: FIX: Also pass the last consumed line's COMMAND's exit status through onchange
Passing the (non-zero) exit status from the last consumed line's COMMAND is difficult, because onchange will periodically invoke ourselves recursively, so we need to use a persisted file that we clear after the first invocation.

diff --git a/bin/onbag b/bin/onbag
--- a/bin/onbag
+++ b/bin/onbag
@@ -11,8 +11,17 @@ isOnChange=
 if [ "$1" = --onchange ]; then
     shift
     isOnChange=t
-    parentScriptPid="$1"
-    shift
+    parentScriptPid="$1"; shift
+    typeset -a runWithPromptPromptArgs=()
+    if [ "$1" = --consumed-exit-status-file ]; then
+	shift
+	consumedExitStatusFilespec="$1"; shift
+	if [ -r "$consumedExitStatusFilespec" ]; then
+	    <"$consumedExitStatusFilespec" IFS=$'\n' read -r exitStatus
+	    rm --force -- "$consumedExitStatusFilespec" 2>/dev/null
+	    runWithPromptPromptArgs=(--initial-status "${exitStatus:-0}")
+	fi
+    fi
 else
     if [ -z "$PGID" ]; then # No parent script has become the process group leader yet.
 	pgid=$(($(ps -o pgid= -p "$$")))	# By defining this, we'll be killing subshell processes of this process group when we're done or interrupted. Any children with the same ambition will defer to us.
@@ -439,7 +448,6 @@ database()
 }
 
 if [ "$isOnChange" ]; then
-    runWithPromptPromptArgs=()
     status=0
     while [ $status -ne $NOOP_SIGNAL -a $status -ne $EXIT_SIGNAL ]
     do
@@ -499,5 +507,16 @@ else
 	onchangeExitOnArg=(--exit-on $EXIT_SIGNAL)
     fi
 
-    ONCHANGE_FILE_MARKER='' onchange "${onchangeArgs[@]}" "${onchangeExitOnArg[@]}" --bare --exec "${BASH_SOURCE[0]}" --onchange $$ "${allArgs[@]}" \; "${BAG:-"${HOME}/.bag"}"
+    typeset -a exitStatusContinuationArgs=()
+    if [ ${exitStatus:-0} -gt 0 ]; then
+	# Passing the (non-zero) exit status from the last consumed line's
+	# COMMAND is difficult, because onchange will periodically invoke
+	# ourselves recursively, so we need to use a persisted file that we
+	# clear after the first invocation.
+	TMPFILE="$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$$RANDOM")"
+	printf '%d\n' "$exitStatus" > "$TMPFILE" && \
+	    exitStatusContinuationArgs=(--consumed-exit-status-file "$TMPFILE")
+    fi
+
+    ONCHANGE_FILE_MARKER='' onchange "${onchangeArgs[@]}" "${onchangeExitOnArg[@]}" --bare --exec "${BASH_SOURCE[0]}" --onchange $$ "${exitStatusContinuationArgs[@]}" "${allArgs[@]}" \; "${BAG:-"${HOME}/.bag"}"
 fi
