pop: Allow combining --lines with --delete and separation of FILE via --

diff --git a/bin/pop b/bin/pop
--- a/bin/pop
+++ b/bin/pop
@@ -7,15 +7,21 @@ Remove the first / N line(s) (or fewer) from (the first non-empty) FILE and
 output it.
 With -d|--delete, an emptied file is removed from the file system as well.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-n|--lines N] [-d|--delete] FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-n|--lines N] [-d|--delete] [--] FILE [...] [-?|-h|--help]'
 }
 lineNum=1
 isDelete=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --lines|-n)		shift; lineNum="$1"; shift;;
-    --delete|-d)	shift; isDelete=t;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--lines|-n)	shift; lineNum="$1"; shift;;
+	--delete|-d)	shift; isDelete=t;;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
