somethingOr: ENH: Also support --skip-* options without --recheck-at-end
Though a recheck should be quick and lightweight, sometimes it cannot be done (because the changes don't take effect immediately). The user still may want to limit the amount of retries. The checking will only be done on the next invocation then.

diff --git a/bin/somethingOr b/bin/somethingOr
--- a/bin/somethingOr
+++ b/bin/somethingOr
@@ -8,7 +8,7 @@
 case "$1" in
     --usage)
 	shift
-	printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" "[-g|--memoize-group GROUP] [--bare|[--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--emulate-prompt] [--worst-status]] [--timespan TIMESPAN[SUFFIX]] [--timeout TIMEOUT[SUFFIX]] [-d|--default c|y|a|l|A|d|n|o|v|N] [--recheck-at-end [--skip-after-num-subsequent-fails N] [--skip-after-num-total-fails N] [--skip-after-fail-for NUMBER[SUFFIX]]] [--recheck-at-checkpoints] ${SOMETHING_USAGE:?} [-?|-h|--help]"
+	printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" "[-g|--memoize-group GROUP] [--bare|[--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--emulate-prompt] [--worst-status]] [--timespan TIMESPAN[SUFFIX]] [--timeout TIMEOUT[SUFFIX]] [-d|--default c|y|a|l|A|d|n|o|v|N] [--recheck-at-end] [--recheck-at-checkpoints] [--skip-after-num-subsequent-fails N] [--skip-after-num-total-fails N] [--skip-after-fail-for NUMBER[SUFFIX]]] ${SOMETHING_USAGE:?} [-?|-h|--help]"
 	printf 'Usage: %q %s <<EOF\n  COMMANDS\nEOF\n' "$(basename "$1")" "[...] ${SOMETHING_USAGE:?}"
 	return
 	;;
@@ -50,17 +50,17 @@ case "$1" in
 			    included anywhere in COMMANDS to do a check. A
 			    successful check will abort additional COMMANDS.
     --skip-after-num-subsequent-fails N
-			    If the recheck fails N times in a row (i.e. without
-			    a sucessful recheck in between), never ask the user
-			    again, and simply ignore ${SOMETHING_WHAT_SUBJECT:?}
-			    from that point.
+			    If the (re)check fails N times in a row (i.e.
+			    without a sucessful recheck in between), never ask
+			    the user again, and simply ignore
+			    ${SOMETHING_WHAT_SUBJECT:?} from that point.
     --skip-after-num-total-fails N
-			    If the recheck fails an overall N times (ignoring
+			    If the (re)check fails an overall N times (ignoring
 			    sucessful rechecks in between), never ask the user
 			    again, and simply ignore ${SOMETHING_WHAT_SUBJECT:?}
 			    from that point.
     --skip-after-fail-for NUMBER[SUFFIX]
-			    If the recheck fails, do not ask the user again
+			    If the (re)check fails, do not ask the user again
 			    within the next NUMBER[SUFFIX], and ignore
 			    ${SOMETHING_WHAT_SUBJECT:?} within
 			    that interval (also for the counting of fails by
@@ -202,6 +202,7 @@ resetSubsequentCounter()
 }
 
 if [ $status -eq 0 ]; then
+    resetSubsequentCounter
     exit 0
 fi
 
@@ -223,6 +224,12 @@ if isSkipAfterNum; then
     fi
 fi
 
+if [ ! "$isRecheckAtEnd" ]; then
+    isSkipped=
+    handleSkipAfterNum || isSkipped=t
+    handleSkipAfterFail || isSkipped=t
+    [ "$isSkipped" ] && exit 1
+fi
 
 memoizeDecision "${memoizeDecisionArgs[@]}" --memoize-group "$group" --subject "${SOMETHING_SUBJECT:?}" --state "${SOMETHING_STATE:?}" --action "${SOMETHING_ACTION:?}" || exit $?
 
